name: Deploy Java Gradle to Azure Web App

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

env:
  AZURE_WEBAPP_NAME: 'your-app-name'   # Azure App Service 이름으로 변경해주세요
  JAVA_VERSION: '17'                   # Azure에서 설정한 Java 버전과 일치해야 합니다 (11, 17, 21 등)
  DISTRIBUTION: 'temurin'              # JDK 배포판 (보통 temurin 또는 zulu 사용)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4

      # 2. JDK 설정 (Java 환경 구성)
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}

      # 3. Gradle 빌드 (권한 부여 및 빌드 실행)
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build

      # 4. Azure App Service로 배포
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Gradle 빌드 결과물인 JAR 파일 경로 지정 (보통 build/libs 폴더에 생성됨)
          package: 'build/libs/*.jar'